[package]
name = "Deck"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.141"
strum = "0.27.2"
strum_macros = "0.27.2"
